version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-postgres
    restart: unless-stopped
    environment:
      HOST: localhost
      POSTGRES_USER: F1sher1998
      POSTGRES_PASSWORD: 159753789
      POSTGRES_DB: noblefi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d financedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local